config/routes.rb
Shredder::Application.routes.draw do
  get "session/create"

  resources :questions
  resources :categories, :only => [:index,:show]
  resources :answers

  match '/login' => 'session#new', :as => 'login'
  match '/logout' => 'session#logout', :as => 'logout'
  delete '/session' => 'session#destroy', :as => 'destroy_session'

  match '/auth/twitter/callback' => 'session#create'

  root :to => 'questions#index'
end

app/models/answer.rb
class Answer < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
    @question = Question.find(params[:question_id])
  end

  def create
    @answer = Answer.new(params[:answer])
    @question = Question.find(params[:question_id])

    @answer.author = current_user

    if @answer.save
      @question.answers << @answer
      redirect_to question_path(@question), :message => 'Answer added'
    else
      render :action => 'new'
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login

protected

  def require_login
    unless logged_in?
      redirect_to login_path
    end
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @_current_user ||= session[:current_user]
  end

  def static_url
    flash[:static_url]
  end

  def active_tab(tab=nil)
    @active_tab = tab if tab
    @active_tab
  end

  helper_method :static_url, :active_tab, :current_user
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Question.all.map {|q| q.catagory}.uniq.sort
  end

  def show
    @questions = Question.all.select {|q| q.catagory == params[:id]}
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = Question.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(params[:question])
    @question.author = current_user

    respond_to do |format|
      if @question.save
        format.html {
          flash[:static_url] = url_for(@question)
          redirect_to @question, notice: 'Question was successfully created.'
        }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :ok }
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :require_login

  def new
  end

  def create
    session[:current_user] = request.env['omniauth.auth']['user_info']['name']
    flash.notice = "Welcome to Shredder, #{current_user}!"
    redirect_to questions_path
  end

  def logout
  end

  def destroy
    reset_session
    redirect_to login_path, :message => 'Logged out'
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def table_view_link(path ,&blk)
    content = capture(&blk)
    link_to content, path
  end

  def toolbar_button(text, path, options)
    config = {}
    options.each do |k,v|
      k = k.to_s
      if %w|icon iconpos direction prefetch rel|.include? k
        k = 'data-' + k
      end
      config[k] = v
    end
    link_to text, path, config
  end

  def toolbar_right_button(text, path, options)
    options['class'] = 'ui-btn-right'
    toolbar_button(text, path, options)
  end

  def footer_nav_item(label, path)
    if active_tab == label
      link_to label, path, 'class' => 'ui-btn-active'
    else
      link_to label, path
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :question_id, @question.id %>

  <div class="field" data-role="fieldcontain">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="actions" data-role="fieldcontain">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/new.html.erb
<% active_tab 'Questions' %>

<div data-role="header" data-position="inline">
  <%= toolbar_button 'Cancel', questions_path, :icon => 'delete', :direction => 'reverse' %>
  <h1>New Answer</h1>
</div>

<div data-role="content">
  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<% active_tab 'Categories' %>

<div data-role="header" data-position="inline">
  <h1>Categories</h1>
  <%= toolbar_right_button 'Add', new_question_path, :iconpos => 'right', :icon => 'plus' %>
</div>

<% if notice %>
  <div id="notice" class="ui-body ui-body-e"><%= notice %></div>
<% end %>

<div data-role="content">
  <ul data-role="listview">
  <% @categories.each do |category| %>
    <li> 
      <%= table_view_link category_path(category) do %>
        <h2><%=category %></h2>
      <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/categories/show.html.erb
<% active_tab 'Categories' %>

<div data-role="header" data-position="inline">
  <%= toolbar_button 'Back', categories_path, :icon => 'arrow-l', :direction => 'reverse' %>
  <h1>Questions</h1>
</div>

<% if notice %>
  <div id="notice" class="ui-body ui-body-e"><%= notice %></div>
<% end %>

<div data-role="content">
  <ul data-role="listview">
  <% @questions.each do |question| %>
    <li> 
      <%= table_view_link question do %>
        <h2><%= question.title %></h2>
        <p><%= question.body %></p>
      <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shredder</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
<body>

<% if static_url %>
<div data-role="page" data-url="<%= static_url %>">
<% else %>
<div data-role="page">
<% end %>
  <%= yield %>
  <div data-role="footer" data-position="fixed" data-id="application-footer">
    <div data-role="navbar">
      <ul>
        <li><%= footer_nav_item 'Questions', questions_path %></li>
        <li><%= footer_nav_item 'Categories', categories_path %></li>
        <li><%= footer_nav_item 'Logout', logout_path %></li>
      </ul>
    </div>
  </div>
</div>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" data-role="fieldcontain">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>
  <div class="field" data-role="fieldcontain">
    <%= f.label :catagory %>
    <%= f.text_field :catagory %>
  </div>
  <div class="actions" data-role="fieldcontain">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<% active_tab 'Questions' %>

<div data-role="header">
  <%= toolbar_button 'Cancel', questions_path, :icon => 'delete', :rel => 'back' %>
  <h1>Question</h1>
</div>

<div data-role="content">
  <%= render 'form' %>
</div>

app/views/questions/index.html.erb
<% active_tab 'Questions' %>

<div data-role="header" data-position="inline">
  <h1>Questions</h1>
  <%= toolbar_right_button 'Add', new_question_path, :iconpos => 'right', :icon => 'plus' %>
</div>

<% if notice %>
  <div id="notice" class="ui-body ui-body-e"><%= notice %></div>
<% end %>

<div data-role="content">
  <ul data-role="listview">
  <% @questions.each do |question| %>
    <li> 
      <%= table_view_link question do %>
        <h2><%= question.title %></h2>
        <p><%= question.body %></p>
      <% end %>
    </li>
  <% end %>
  </ul>
</div>

app/views/questions/new.html.erb
<% active_tab 'Questions' %>

<div data-role="header" data-position="inline">
  <%= toolbar_button 'Cancel', questions_path, :icon => 'delete', :direction => 'reverse' %>
  <h1>New Question</h1>
</div>

<div data-role="content">
  <%= render 'form' %>
</div>

app/views/questions/show.html.erb
<% active_tab 'Questions' %>

<div data-role="header">
  <%= toolbar_button 'Back', questions_path, :icon => 'arrow-l', :direction => 'reverse' %>
  <h1>Question</h1>
  <%= toolbar_right_button 'Edit', edit_question_path(@question),
    :iconpos => 'right', :icon => 'gear' %>
</div>

<% if notice %>
  <div id="notice" class="ui-body ui-body-e"><%= notice %></div>
<% end %>

<div data-role="content">
  <h2><%= @question.title %></h2>
  <p><%= @question.body %></p>
  
  <p class="question-attribution">
    &mdash; <em><%= @question.author %>, <%= distance_of_time_in_words @question.created_at, Time.now %> ago.</em>
  </p>
  
  <p class="question-catagory">Catagory: <span class="label"><%= @question.catagory %></p>

  <ul>
  <% @question.answers.each do |answer| %>
    <li><%= answer.body %> &mdash <%= answer.author %></li>
  <% end %>
  </ul>

  <%= link_to 'Add An Answer', new_answer_path(:question_id => @question.id), 'data-role' => 'button' %>
</div>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/logout.html.erb
<% active_tab 'Logout' %>

<div data-role="header">
  <h1>Logout</h1>
</div>

<div data-role="content">
  <h2>Logout</h2>
  <p>You are currently logged in as <%= current_user %>. Hit the button below to
  logout of the system.</p>

  <%= button_to 'Logout', destroy_session_path, :method => :delete, 'data-role' => 'button' %>
</div>

app/views/session/new.html.erb
<div data-role="header">
  <h1>Login Required</h1>
</div>

<div data-role="content">
  <h1>Logging in</h1>

  <p>This application requires you to log in using a Twitter account.  Clicking
  the button below will transfer you to a Twitter page, which will ask you if
  you'd like to authorize this application.  Select yes and you will be
  redirected back to the appliction.</p>

  <%= link_to 'Login', '/auth/twitter', 'data-role' => 'button', 'rel' => 'external' %>

  <p><strong>Note:</strong>Once you have authorized this application, when you
push the login button, you'll automatically be logged in without asking for
confirmation. If you'd like to log in with a different account, you'll have to
log out of <a href="http://twitter.com/logout" rel="external">twitter first</a>,
then come back to this app.</p>

</div>